### PR TITLE
PCO2W Corrections

### PR DESCRIPTION
**Pull request by cwingard**
Recalculates blanks and factory calibration coefficients to correctly determine pCO2. Based on updated vendor code.

@desiderr @lgarzio Please review and merge

### CODE REVIEW

**Review by danmergens — CHANGES_REQUESTED** [review]
Should have a test that causes the error seen previously and now works for the update (e.g. test_13127).

Seth Foote was tasked to work the ticket, I'll add him to the review to make sure we get everything included (update the function calls to remove ea434, eb434, ea620, eb620 in ion-functions and preload and calibration files). Possibly just deprecate those parameters for now, and remove them later.

Finally - do we only have Sunburst PCO2W instruments using these functions? If there are others, will these hard-coded constants suffice?

**Comment by desiderr** [comment]
Leave a comment

**Comment by desiderr** [comment]
Dan - What is the purpose of a test that shows that incorrect test values, calculated by the deprecated incorrect code, are not calculated by the corrected code? I can see a reason if the DPA code is reverted to the incorrect version while the test functions are not reverted, but I wouldn't expect that that would happen. Note that I have an open pull request (#10) made in June which also corrects incorrect vendor code (for VEL3D-K).

**Comment by danmergens** [comment]
The test will serve two purposes; it will demonstrate that the code no longer has the issue and it will flag any regression in the code (ensure that this case is tested for every time the code is updated). Unit tests are run every time a pull request is submitted.

**Comment by desiderr** [comment]
I believe that the current unit tests that Chris wrote already do that. 

Are you suggesting that the old incorrect code be executed in the unit tests every time a unit test is run?

**Comment by danmergens** [comment]
No, I'm not suggesting that. It appeared that the test was modified, but it wasn't clear that it was specifically testing for the issue being corrected. If it is (running the old code against the new test would produce the error reported in the Redmine issue), we can proceed to merge the change as it is. I was just pointing out that TravisCI runs the unit tests every time code is submitted. SOP is that we create a unit test specific to the fix we are implementing. This is preferred over updating other parts of the unit test as it increases the chances of regression.

**Comment by desiderr** [comment]
OK, to be clear: the specific issue was that the old DPA algorithm was incorrect; its unit test values were obviously calculated using this incorrect algorithm. The pull request fixes the algorithm itself and provides new unit test values for the new corrected code. Automatically, therefore, the new unit tests are specific to the fix being implemented. That would indicate that the change can be merged as it is.

**Comment by danmergens** [comment]
Thanks for the clarification. I'll approve and merge.

**Review by danmergens — APPROVED** [review]

**Pull request merged**
